export const topics = [
  "Plastic pollution",
  "Outdoor air pollution",
  "Polio",
  "Population Growth",
  "Age Structure",
  "Gender Ratio",
  "Life Expectancy",
  "Fertility Rate",
  "Child & Infant Mortality",
  "Urbanization",
  "Migration",
  "Global Health",
  "Causes of Death",
  "Burden of Disease",
  "Mental Health",
  "Suicides",
  "Cardiovascular Diseases",
  "Cancer",
  "Maternal Mortality",
  "Air Pollution",
  "Lead Pollution",
  "Alcohol Consumption",
  "Illicit Drug Use",
  "Obesity",
  "Smoking",
  "Pandemics",
  "COVID-19",
  "Malaria",
  "HIV/AIDS",
  "Diarrheal Diseases",
  "Tuberculosis",
  "Neglected Tropical Diseases",
  "Influenza",
  "Pneumonia",
  "Tetanus",
  "Mpox (monkeypox)",
  "Smallpox",
  "Eradication of Diseases",
  "Vaccination",
  "Antibiotics & Antibiotic Resistance",
  "Healthcare Spending",
  "Climate Change",
  "CO2 & Greenhouse Gas Emissions",
  "Ozone Layer",
  "Energy",
  "Access to Energy",
  "Energy Mix",
  "Fossil Fuels",
  "Nuclear Energy",
  "Renewable Energy",
  "Metals & Minerals",
  "Natural Disasters",
  "Biodiversity",
  "Environmental Impacts of Food Production",
  "Fish & Overfishing",
  "Animal Welfare",
  "Land Use",
  "Water Use & Stress",
  "Forests & Deforestation",
  "Wildfires",
  "Oil Spills",
  "Waste Management",
  "Clean Water",
  "Sanitation",
  "Agricultural Production",
  "Meat & Dairy Production",
  "Crop Yields",
  "Farm Size",
  "Fertilizers",
  "Pesticides",
  "Employment in Agriculture",
  "Hunger & Undernourishment",
  "Food Supply",
  "Food Prices",
  "Diet Compositions",
  "Micronutrient Deficiency",
  "Human Height",
  "Poverty",
  "Economic Growth",
  "Economic Inequality",
  "Foreign Aid",
  "Economic Inequality by Gender",
  "Government Spending",
  "State Capacity",
  "Taxation",
  "Corruption",
  "Education Spending",
  "Military Personnel & Spending",
  "Women's Employment",
  "Child Labor",
  "Working Hours",
  "Trade & Globalization",
  "Tourism",
  "Research & Development",
  "Internet",
  "Books",
  "Technological Change",
  "Artificial Intelligence",
  "Space Exploration & Satellites",
  "Transport",
  "Homelessness",
  "Light at Night",
  "Marriages & Divorces",
  "Loneliness & Social Connections",
  "Trust",
  "Happiness & Life Satisfaction",
  "Human Development Index (HDI)",
  "Human Rights",
  "Democracy",
  "Women's Rights",
  "LGBT+ Rights",
  "War & Peace",
  "Nuclear Weapons",
  "Homicides",
  "Terrorism",
  "Violence Against Children & Children's Rights",
];

export const countries = [
  { name: "Poland", flag: "🇵🇱" },
  { name: "French Polynesia", flag: "🇵🇫" },
  { name: "United States", flag: "🇺🇸" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "France", flag: "🇫🇷" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "China", flag: "🇨🇳" },
  { name: "India", flag: "🇮🇳" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "Russia", flag: "🇷🇺" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "Mexico", flag: "🇲🇽" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "Egypt", flag: "🇪🇬" },
  { name: "Turkey", flag: "🇹🇷" },
  { name: "South Korea", flag: "🇰🇷" },
  { name: "Indonesia", flag: "🇮🇩" },
  { name: "Saudi Arabia", flag: "🇸🇦" },
  { name: "Israel", flag: "🇮🇱" },
  { name: "Sweden", flag: "🇸🇪" },
  { name: "Norway", flag: "🇳🇴" },
  { name: "Denmark", flag: "🇩🇰" },
  { name: "Finland", flag: "🇫🇮" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "Belgium", flag: "🇧🇪" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Greece", flag: "🇬🇷" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Ireland", flag: "🇮🇪" },
  { name: "New Zealand", flag: "🇳🇿" },
  { name: "Singapore", flag: "🇸🇬" },
  { name: "Malaysia", flag: "🇲🇾" },
  { name: "Thailand", flag: "🇹🇭" },
  { name: "Vietnam", flag: "🇻🇳" },
  { name: "Philippines", flag: "🇵🇭" },
  { name: "Pakistan", flag: "🇵🇰" },
  { name: "Bangladesh", flag: "🇧🇩" },
  { name: "Sri Lanka", flag: "🇱🇰" },
  { name: "Nepal", flag: "🇳🇵" },
  { name: "Bhutan", flag: "🇧🇹" },
  { name: "Maldives", flag: "🇲🇻" },
  { name: "Afghanistan", flag: "🇦🇫" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Iraq", flag: "🇮🇶" },
  { name: "Syria", flag: "🇸🇾" },
  { name: "Lebanon", flag: "🇱🇧" },
  { name: "Jordan", flag: "🇯🇴" },
  { name: "Palestine", flag: "🇵🇸" },
  { name: "Kuwait", flag: "🇰🇼" },
  { name: "Bahrain", flag: "🇧🇭" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "Oman", flag: "🇴🇲" },
  { name: "Yemen", flag: "🇾🇪" },
  { name: "Kazakhstan", flag: "🇰🇿" },
  { name: "Uzbekistan", flag: "🇺🇿" },
  { name: "Turkmenistan", flag: "🇹🇲" },
  { name: "Kyrgyzstan", flag: "🇰🇬" },
  { name: "Tajikistan", flag: "🇹🇯" },
  { name: "Mongolia", flag: "🇲🇳" },
  { name: "North Korea", flag: "🇰🇵" },
  { name: "Myanmar", flag: "🇲🇲" },
  { name: "Laos", flag: "🇱🇦" },
  { name: "Cambodia", flag: "🇰🇭" },
  { name: "Brunei", flag: "🇧🇳" },
  { name: "East Timor", flag: "🇹🇱" },
  { name: "Papua New Guinea", flag: "🇵🇬" },
  { name: "Fiji", flag: "🇫🇯" },
  { name: "Solomon Islands", flag: "🇸🇧" },
  { name: "Vanuatu", flag: "🇻🇺" },
  { name: "Samoa", flag: "🇼🇸" },
  { name: "Tonga", flag: "🇹🇴" },
  { name: "Tuvalu", flag: "🇹🇻" },
  { name: "Nauru", flag: "🇳🇷" },
  { name: "Kiribati", flag: "🇰🇮" },
  { name: "Marshall Islands", flag: "🇲🇭" },
  { name: "Palau", flag: "🇵🇼" },
  { name: "Micronesia", flag: "🇫🇲" },
  { name: "Cook Islands", flag: "🇨🇰" },
  { name: "Niue", flag: "🇳🇺" },
  { name: "Tokelau", flag: "🇹🇰" },
  { name: "Wallis and Futuna", flag: "🇼🇫" },
  { name: "New Caledonia", flag: "🇳🇨" },
  { name: "Pitcairn Islands", flag: "🇵🇳" },
  { name: "Norfolk Island", flag: "🇳🇫" },
  { name: "Christmas Island", flag: "🇨🇽" },
  { name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { name: "Heard Island and McDonald Islands", flag: "🇭🇲" },
  { name: "Macquarie Island", flag: "🇲🇶" },
  { name: "Antarctica", flag: "🇦🇶" },
  { name: "South Georgia and the South Sandwich Islands", flag: "🇬🇸" },
  { name: "Falkland Islands", flag: "🇫🇰" },
  { name: "Saint Helena", flag: "🇸🇭" },
  { name: "Ascension Island", flag: "🇦🇨" },
  { name: "Tristan da Cunha", flag: "🇹🇦" },
  { name: "Bouvet Island", flag: "🇧🇻" },
  { name: "South Sudan", flag: "🇸🇸" },
  { name: "Western Sahara", flag: "🇪🇭" },
  { name: "Kosovo", flag: "🇽🇰" },
  { name: "Taiwan", flag: "🇹🇼" },
  { name: "Hong Kong", flag: "🇭🇰" },
  { name: "Macau", flag: "🇲🇴" },
  { name: "Greenland", flag: "🇬🇱" },
  { name: "Faroe Islands", flag: "🇫🇴" },
  { name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
  { name: "Åland Islands", flag: "🇦🇽" },
  { name: "Gibraltar", flag: "🇬🇮" },
  { name: "Guernsey", flag: "🇬🇬" },
  { name: "Jersey", flag: "🇯🇪" },
  { name: "Isle of Man", flag: "🇮🇲" },
  { name: "Bermuda", flag: "🇧🇲" },
  { name: "British Virgin Islands", flag: "🇻🇬" },
  { name: "Cayman Islands", flag: "🇰🇾" },
  { name: "Montserrat", flag: "🇲🇸" },
  { name: "Anguilla", flag: "🇦🇮" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { name: "Antigua and Barbuda", flag: "🇦🇬" },
  { name: "Dominica", flag: "🇩🇲" },
  { name: "Saint Lucia", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { name: "Barbados", flag: "🇧🇧" },
  { name: "Grenada", flag: "🇬🇩" },
  { name: "Trinidad and Tobago", flag: "🇹🇹" },
  { name: "Aruba", flag: "🇦🇼" },
  { name: "Curaçao", flag: "🇨🇼" },
  { name: "Sint Maarten", flag: "🇸🇽" },
  { name: "Bonaire", flag: "🇧🇶" },
  { name: "Saba", flag: "🇧🇶" },
  { name: "Sint Eustatius", flag: "🇧🇶" },
  { name: "Saint Barthélemy", flag: "🇧🇱" },
  { name: "Saint Martin", flag: "🇲🇫" },
  { name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
]; // Sample search results
export const sampleResults = [
  {
    title: "Global CO2 Emissions",
    subtitle: "Interactive chart showing historical trends by country",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Malaria Deaths by Region",
    subtitle:
      "Africa continues to bear the highest burden of malaria mortality",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Child Mortality Trends 1950-2022",
    subtitle: "Significant improvements across most countries over time",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Renewable Energy Adoption",
    subtitle: "Solar and wind capacity growth in major economies",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Plastic Pollution in Oceans",
    subtitle: "Distribution of plastic waste and environmental impacts",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Income Inequality Metrics",
    subtitle: "Gini coefficients and wealth distribution across countries",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Air Pollution Health Effects",
    subtitle: "Correlation between PM2.5 exposure and respiratory diseases",
    image: "https://placeholderjs.com/300x200",
  },
  {
    title: "Global Vaccination Coverage",
    subtitle: "Percentage of population vaccinated by country and disease",
    image: "https://placeholderjs.com/300x200",
  },
];
